//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdezhdaDlyaRuchek.AppData
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Materials
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int MaterialTypeID { get; set; }
        public Nullable<int> PossibleProvidersID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public int WarehouseCount { get; set; }
        public int MinimumCount { get; set; }
        public int BoxCount { get; set; }
        public string Unit { get; set; }

        public string ImgPath
        {
            get
            {
                return "/Resources" + Image;
            }
        }

        public string ReminderStock
        {
            get
            {
                return "Остаток: " + WarehouseCount + " шт";
            }
        }

        public string MinimumMaterial
        {
            get
            {
                return "   Минимальное количество: " + MinimumCount + " шт";
            }
        }

        public string ColorBrush
        {
            get
            {
                if (WarehouseCount < MinimumCount)
                    return "#f19292";
                else if (WarehouseCount > MinimumCount * 4)
                    return "#ffba01";
                else
                    return "";
            }
        } 

    
        public virtual MaterialType MaterialType { get; set; }
        public virtual PossibleProviders PossibleProviders { get; set; }
    }
}
