//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdezhdaDlyaRuchek.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleProviders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PossibleProviders()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ProviderTypeID { get; set; }
        public string INN { get; set; }
        public Nullable<int> RatingOfQuility { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual ProviderType ProviderType { get; set; }
    }
}
